# Generated by Django 5.0.4 on 2024-05-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ryugiohproject_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="description",
            new_name="desc",
        ),
        migrations.RemoveField(
            model_name="card",
            name="attack_points",
        ),
        migrations.RemoveField(
            model_name="card",
            name="defense_points",
        ),
        migrations.AddField(
            model_name="card",
            name="atk",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="attribute",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="card_images",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="card_prices",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="defense",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="frameType",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="race",
            field=models.CharField(default="Dragon", max_length=100),
        ),
        migrations.AddField(
            model_name="card",
            name="type",
            field=models.CharField(default="Normal", max_length=100),
        ),
    ]
