# Generated by Django 5.0.4 on 2024-05-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ryugiohproject_app", "0003_card_set_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="card",
            name="set_name",
        ),
        migrations.AlterField(
            model_name="card",
            name="card_images",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="race",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="card",
            name="type",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="card",
            name="sets",
            field=models.ManyToManyField(
                related_name="cards", to="Ryugiohproject_app.cardset"
            ),
        ),
    ]
